#!/bin/bash

#BSUB -J POISSON
#BSUB -o poisson_sim%J.out
#BSUB -q hpcintro
#BSUB -W 5
#BSUB -n 4
#BSUB -R "rusage[mem=8GB]"

module load gcc/8.2.0
module load studio

EXECUTABLE=main.gcc

# define any command line options for your executable here
# EXECOPTS=

# set some OpenMP variables here
export OMP_NUM_THREADS=$LSB_DJOB_NUMPROC
#
# keep idle threads spinning (needed to monitor idle times!)
export OMP_WAIT_POLICY=active
#
# if you use a runtime schedule, define it below
#export OMP_SCHEDULE=


# experiment name

JID=${LSB_JOBID}
EXPOUT="$LSB_JOBNAME.${JID}.er"

# start the collect command with the above settings
collect -o $EXPOUT ./$EXECUTABLE $EXECOPTS
